framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        #Poniżej zdefiniowaliśmy domyslnie nadawce wiadomości.
        #envelope:
        #    sender: "%env(string:default:default_admin_email:ADMIN_EMAIL)%"
