twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    paths:
        'public/images': images
        'assets/styles': email_styles
        #link do zdjęć, drugi element po : moze być dowolny.

when@test:
    twig:
        strict_variables: true
